<#
.SYNOPSIS
    Submits a multi-step workflow and prints the result of every step.

.DESCRIPTION
    Exercises both execution paths at once:
      * research.* is routed to the Scout adapter, which calls the local bridge and
        therefore a Microsoft Foundry agent;
      * foundry.chat is executed by the built-in adapter against the model deployment
        the orchestrator bound to the step;
      * fs.write and shell.exec run inside the node's sandbox on the VM itself.

.EXAMPLE
    .\demo-workflow.ps1 -ApiKey "<key>"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ApiKey,
    [string]$BaseUrl = "http://localhost:8000",
    [int]$TimeoutSeconds = 180
)

$ErrorActionPreference = "Stop"
$headers = @{ "X-API-Key" = $ApiKey; "Content-Type" = "application/json" }

Write-Host "== Fleet" -ForegroundColor Cyan
$agents = Invoke-RestMethod "$BaseUrl/api/v1/agents" -Headers $headers
if (-not $agents) { throw "No agents registered. Start a node first." }
$agents | Format-Table agent_id, status, framework, platform, active_tasks

Write-Host "== Model catalog" -ForegroundColor Cyan
Invoke-RestMethod "$BaseUrl/api/v1/models" -Headers $headers |
    Format-Table name, model_name, status, capabilities

$workflow = @{
    name  = "Fleet capability demo"
    steps = @(
        @{
            step_id = "research"
            title   = "Research via Foundry agent"
            action  = "research.brief"
            payload = @{
                prompt = "List three concrete risks of storing model API keys on virtual machines. One sentence each."
            }
        },
        @{
            step_id    = "synthesise"
            title      = "Synthesise with a bound deployment"
            action     = "foundry.chat"
            depends_on = @("research")
            payload    = @{
                system = "You are a concise technical writer."
                prompt = "Write a three-sentence executive summary explaining why managed identity removes the need for API keys on VMs."
            }
            required_model_capabilities = @("chat")
        },
        @{
            step_id    = "persist"
            title      = "Persist the report on the node"
            action     = "fs.write"
            depends_on = @("synthesise")
            payload    = @{
                path    = "reports/summary.txt"
                content = "Generated by the Hecaton fleet demo."
            }
        },
        @{
            step_id = "inventory"
            title   = "Collect host inventory"
            action  = "shell.exec"
            payload = @{ command = "disk_report" }
        }
    )
}

Write-Host "== Submitting workflow" -ForegroundColor Cyan
$submitted = Invoke-RestMethod -Method Post "$BaseUrl/api/v1/workflows" `
    -Headers $headers -Body ($workflow | ConvertTo-Json -Depth 10)
$workflowId = $submitted.workflow_id
Write-Host "   workflow_id = $workflowId"

$deadline = (Get-Date).AddSeconds($TimeoutSeconds)
do {
    Start-Sleep -Seconds 3
    $view = Invoke-RestMethod "$BaseUrl/api/v1/workflows/$workflowId" -Headers $headers
    $states = ($view.tasks | ForEach-Object { "$($_.step_id)=$($_.status)" }) -join "  "
    Write-Host "   [$($view.status)] $states"
} while ($view.status -eq "running" -and (Get-Date) -lt $deadline)

Write-Host ""
Write-Host "== Workflow $($view.status)" -ForegroundColor Cyan
foreach ($task in $view.tasks) {
    Write-Host ""
    Write-Host "--- $($task.step_id) [$($task.status)] on $($task.agent_id)" -ForegroundColor Yellow
    if ($task.error) { Write-Host "    error: $($task.error)" -ForegroundColor Red }
    if ($task.result) { $task.result | ConvertTo-Json -Depth 8 }
}

Write-Host ""
Write-Host "== Token usage" -ForegroundColor Cyan
Invoke-RestMethod "$BaseUrl/api/v1/metrics/summary" -Headers $headers | ConvertTo-Json -Depth 6
